name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev

    - name: Run pre-commit
      run: poetry run pre-commit run --all-files

    - name: Build Docker image
      run: docker build -t watchsync-test .

    - name: Run tests in Docker container
      run: docker run --name watchsync-container watchsync-test

    - name: Copy coverage report
      run: docker cp watchsync-container:/watchsync/htmlcov ./

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov

    - name: Clean up
      run: docker rm watchsync-container
